TrajectoryPlannerROS:
  max_vel_x: 0.35
  min_vel_x: 0.1
  min_vel_theta: 0.5
  max_vel_theta: 1.25
  min_in_place_vel_theta: 0.5
  # Backup velocity
  escape_vel: -0.4  

  acc_lim_theta: 10.0
  acc_lim_x: 2.5
  acc_lim_y: 2.5

  holonomic_robot: false

  yaw_goal_tolerance: 6.28
  xy_goal_tolerance: 0.1

  sim_time: 1.0
  vx_samples: 2
  vtheta_samples: 10