axis_linear: 1  # Left thumb stick vertical
scale_linear: 1.25
scale_linear_turbo: 2.5

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 4
scale_angular_turbo: 12.0

enable_button: 5  # Left trigger button
enable_turbo_button: 4  # Right trigger button
