# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

topics:
-
  name    : navigation
  topic   : nav_vel
  timeout : 0.5
  priority: 10
-
  name    : gps_heading
  topic   : nav_vel_heading
  timeout : 0.5
  priority: 20
-
  name    : 3vistor_vel
  topic   : sickToF/nav_vel
  timeout : 1.0
  priority: 25
-
  name    : camera_stitch
  topic   : camera_stitch/cmd_vel
  timeout : 0.5
  priority: 30
-
  name    : joystick
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 100